(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(load custom-file)

(add-to-list 'load-path (expand-file-name "src" user-emacs-directory))
(load-library "core")
(load-library "vendor")
(load-library "tasks")
(load-library "sticky-note")
(load-library "sidebar")
(load-library "utils")
